#!/bin/bash

echo "$DOCKERFILE_PATH"

echo "Current Path: `pwd`"
echo "Files: \n`ls -l`"

echo "Vars: "
set

docker build --build-arg ALPINE_VERSION=3.8 --build-arg GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc/releases/download -f $DOCKERFILE_PATH -t $IMAGE_NAME .